# Generated by Django 3.2.6 on 2021-10-13 16:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211011_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 17, 1, 51, 552578, tzinfo=utc)),
        ),
    ]
