# Generated by Django 3.2.6 on 2021-10-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_stripecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecard',
            name='exp_month',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='stripecard',
            name='exp_year',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='stripecard',
            name='last4',
            field=models.CharField(default=None, max_length=4, null=True),
        ),
    ]
