# Generated by Django 3.2.6 on 2021-11-10 16:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20211110_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(default=uuid.uuid4, max_length=50, null=True),
        ),
    ]
