"""Update Game model.

Revision ID: 69d1341f966e
Revises: 03b9881c09d2
Create Date: 2021-11-22 20:05:16.926965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69d1341f966e'
down_revision = '03b9881c09d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('moves', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'moves')
    # ### end Alembic commands ###
