"""update_pizza__add_size_column

Revision ID: e9c92565f447
Revises: 4c76c573a64e
Create Date: 2021-08-23 20:49:12.746465

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e9c92565f447'
down_revision = '4c76c573a64e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pizza', sa.Column('size', mysql.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pizza', 'size')
    # ### end Alembic commands ###
